#!name=工银e生活
#!desc=Remove TikTok's regional restrictions.
[Script]
icbccookie.js=type=http-request, require-body=1,pattern=^https:\/\/icbc1\.wlphp\.com:8444\/js\/api\/index\/signIn,script-path=https://raw.githubusercontent.com/barrym-chen/Script/master/icbc/icbc_cookie.js
icbcsign.js=cron,cronexp=11 0 * * *,script-path=https://raw.githubusercontent.com/barrym-chen/Script/master/icbc/icbc_sign.js

[MIMT]
hostname = icbc1.wlphp.com:8444
