#!name=iqiyi-daily
#!desc=Remove TikTok's regional restrictions.

[Script]
爱奇艺签到 = type=cron,cronexp=8 0 * * *,script-path=https://raw.githubusercontent.com/NobyDa/Script/master/iQIYI-DailyBonus/iQIYI.js

爱奇艺获取Cookie = type=http-request,pattern=^https?:\/\/iface(\d)?\.iqiyi\.com\/,script-path=https://raw.githubusercontent.com/NobyDa/Script/master/iQIYI-DailyBonus/iQIYI.js

[MITM] 
hostname= ifac*.iqiyi.com
