#!name=半点红包雨,集鞭炮,神仙书院
#!desc=Remove TikTok's regional restrictions.
[Script]
半点红包雨 = type=cron,cronexp=30,31 12-23/1 * * *,wake-system=1,timeout=60,script-path=https://raw.githubusercontent.com/shylocks/Loon/main/jd_live_redrain_half.js
//集鞭炮赢京豆
type=cron,cronexp="10 8,21 * * *",wake-system=1,timeout=2220,script-path=https://raw.githubusercontent.com/LXK9301/jd_scripts/master/jd_firecrackers.js
京东神仙书院 = type=cron,cronexp=0 8 * * *,wake-system=1,timeout=60,script-path=https://qxzy.top/rules/QuantumultX/js/jd_immortal.js
海产新年抽奖 = type=cron,cronexp="10 7 * * *",wake-system=1,timeout=200,script-path=https://raw.githubusercontent.com/shylocks/Loon/main/jd_sx.js
京东手机年终奖 = type=cron,cronexp="30 9 * * *",wake-system=1,timeout=200,script-path=https://raw.githubusercontent.com/shylocks/Loon/main/jd_festival.js
