#!name=meituan-daily
#!desc=Remove TikTok's regional restrictions.

[MITM]
hostname = i.meituan.com

[Script]
//http-request ^https:\/\/i.meituan.com\/evolve\/signin\/signpost\/ script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/meituan/meituan.cookie.js, requires-body=true
cron "20 0 0 * * *" script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/meituan/meituan.js
