#!name=规则
#!desc=

[Rule]
DOMAIN-SUFFIX,ft.com,🇬🇧 UK London 02
DOMAIN-KEYWORD,DISNEY,🇭🇰 Hong Kong 02
DOMAIN-KEYWORD,nytimes,🇺🇸 USA Seattle 02
DOMAIN-KEYWORD,dowjones,🇺🇸 USA Seattle 02
DOMAIN-KEYWORD,hulu,🇭🇰 Hong Kong 02
DOMAIN-KEYWORD,washingtonpost,🇺🇸 USA Seattle 03
DOMAIN-KEYWORD,wpdigital,🇺🇸 USA Seattle 03
DOMAIN-KEYWORD,m-team,🇭🇰 Hong Kong 02
DOMAIN-KEYWORD,sling,🇺🇸 USA Seattle 02
DOMAIN-KEYWORD,pandora,🇺🇸 USA Seattle 02
DOMAIN-KEYWORD,pikpak,🇭🇰 Hong Kong 02
DOMAIN-KEYWORD,evernote,DIRECT
DOMAIN-KEYWORD,teamviewer,DIRECT
DOMAIN-KEYWORD,setapp,DIRECT
# DOMAIN-KEYWORD,emby,DIRECT
# DOMAIN-KEYWORD,plex,DIRECT
DOMAIN-KEYWORD,parsec,DIRECT
# DEST-PORT,8096,DIRECT
# DEST-PORT,32400,DIRECT
# DEST-PORT,11707,DIRECT
# DOMAIN-KEYWORD,synology,DIRECT
# PROCESS-NAME,/Applications/Plex Media Server.app/Contents/MacOS/Plex Media Server,DIRECT
# PROCESS-NAME,/Applications/Plex.app/Contents/MacOS/Plex,DIRECT
DOMAIN-SUFFIX,kiddoe.top,DIRECT
#IP-CIDR,172.98.12.0/24,🇨🇦 Canada 02
#IP-CIDR,209.209.11.0/24,🇨🇦 Canada 02
#IP-CIDR,167.235.204.0/24,🇩🇪 Germany 02
#IP-CIDR,167.235.251.0/24,🇩🇪 Germany 02
DOMAIN-KEYWORD,belle,🇭🇰 Hong Kong 02
DOMAIN-KEYWORD,openai,🇺🇸 USA Seattle 02
DOMAIN-KEYWORD,chatgpt,🇺🇸 USA Seattle 02
DOMAIN-KEYWORD,your-storagebox,Akko
DOMAIN-KEYWORD,m-team,🇨🇳 Taiwan 02
DOMAIN-KEYWORD,roamresearch,🇭🇰 Hong Kong 02
DEST-PORT,22,DIRECT

# IP-CIDR,206.190.239.0/24,DIRECT
# PROCESS-NAME,/Applications/qbittorrent.app/Contents/MacOS/qbittorrent,DIRECT
# SRC-IP,192.168.100.236,DIRECT

DOMAIN-KEYWORD,amazon,🇸🇬 Singapore 02
DOMAIN-SUFFIX,cloudfront.net,🇸🇬 Singapore 02
DOMAIN-SUFFIX,aiv-cdn.net,🇸🇬 Singapore 02
DOMAIN-SUFFIX,aiv-delivery.net,🇸🇬 Singapore 02
DOMAIN-SUFFIX,amazonprimevideo.cn,🇸🇬 Singapore 02
DOMAIN-SUFFIX,amazonprimevideo.com.cn,🇸🇬 Singapore 02
DOMAIN-SUFFIX,amazonprimevideos.com,🇸🇬 Singapore 02
DOMAIN-SUFFIX,amazonvideo.cc,🇸🇬 Singapore 02
DOMAIN-SUFFIX,amazonvideo.com,🇸🇬 Singapore 02
DOMAIN-SUFFIX,atv-ps.amazon.com,🇸🇬 Singapore 02
DOMAIN-SUFFIX,avodmp4s3ww-a.akamaihd.net,🇸🇬 Singapore 02
DOMAIN-SUFFIX,fls-na.amazon.com,🇸🇬 Singapore 02
DOMAIN-SUFFIX,llnwd.net,🇸🇬 Singapore 02
DOMAIN-SUFFIX,media-amazon.com,🇸🇬 Singapore 02
DOMAIN-SUFFIX,prime-video.com,🇸🇬 Singapore 02
DOMAIN-SUFFIX,primevideo.cc,🇸🇬 Singapore 02
DOMAIN-SUFFIX,primevideo.com,🇸🇬 Singapore 02
DOMAIN-SUFFIX,primevideo.info,🇸🇬 Singapore 02
DOMAIN-SUFFIX,primevideo.org,🇸🇬 Singapore 02
DOMAIN-SUFFIX,primevideo.tv,🇸🇬 Singapore 02
DOMAIN-KEYWORD,avoddashs,🇸🇬 Singapore 02
USER-AGENT,InstantVideo.US*,🇸🇬 Singapore 02
USER-AGENT,Prime%20Video*,🇸🇬 Singapore 02
PROCESS-NAME,com.amazon.avod.thirdpartyclient,🇸🇬 Singapore 02

DOMAIN,wmff.warnermediacdn.com,🇨🇳 Taiwan 02
DOMAIN-SUFFIX,bcbolthboa-a.akamaihd.net,🇨🇳 Taiwan 02
DOMAIN-SUFFIX,cf-images.ap-southeast-1.prod.boltdns.net,🇨🇳 Taiwan 02
DOMAIN-SUFFIX,cinemax.com,🇨🇳 Taiwan 02
DOMAIN-SUFFIX,dai3fd1oh325y.cloudfront.net,🇨🇳 Taiwan 02
DOMAIN-SUFFIX,execute-api.ap-southeast-1.amazonaws.com,🇨🇳 Taiwan 02
DOMAIN-SUFFIX,execute-api.us-east-1.amazonaws.com,🇨🇳 Taiwan 02
DOMAIN-SUFFIX,forthethrone.com,🇨🇳 Taiwan 02
DOMAIN-SUFFIX,hbo.com,🇨🇳 Taiwan 02
DOMAIN-SUFFIX,hboasia.com,🇨🇳 Taiwan 02
DOMAIN-SUFFIX,hboasia1-i.akamaihd.net,🇨🇳 Taiwan 02
DOMAIN-SUFFIX,hboasia2-i.akamaihd.net,🇨🇳 Taiwan 02
DOMAIN-SUFFIX,hboasia3-i.akamaihd.net,🇨🇳 Taiwan 02
DOMAIN-SUFFIX,hboasia4-i.akamaihd.net,🇨🇳 Taiwan 02
DOMAIN-SUFFIX,hboasia5-i.akamaihd.net,🇨🇳 Taiwan 02
DOMAIN-SUFFIX,hboasialive.akamaized.net,🇨🇳 Taiwan 02
DOMAIN-SUFFIX,hbogeo.cust.footprint.net,🇨🇳 Taiwan 02
DOMAIN-SUFFIX,hbogo.com,🇨🇳 Taiwan 02
DOMAIN-SUFFIX,hbogoasia.com,🇨🇳 Taiwan 02
DOMAIN-SUFFIX,hbogoasia.hk,🇨🇳 Taiwan 02
DOMAIN-SUFFIX,hbogoprod-vod.akamaized.net,🇨🇳 Taiwan 02
DOMAIN-SUFFIX,hbolb.onwardsmg.com,🇨🇳 Taiwan 02
DOMAIN-SUFFIX,hbomax.com,🇨🇳 Taiwan 02
DOMAIN-SUFFIX,hbomaxcdn.com,🇨🇳 Taiwan 02
DOMAIN-SUFFIX,hbonow.com,🇨🇳 Taiwan 02
DOMAIN-SUFFIX,hbounify-prod.evergent.com,🇨🇳 Taiwan 02
DOMAIN-SUFFIX,manifest.prod.boltdns.net,🇨🇳 Taiwan 02
DOMAIN-SUFFIX,maxgo.com,🇨🇳 Taiwan 02
DOMAIN-SUFFIX,now-ashare.com,🇨🇳 Taiwan 02
DOMAIN-SUFFIX,now-tv.com,🇨🇳 Taiwan 02
DOMAIN-SUFFIX,now.com,🇨🇳 Taiwan 02
DOMAIN-SUFFIX,now.com.hk,🇨🇳 Taiwan 02
DOMAIN-SUFFIX,nowe.com,🇨🇳 Taiwan 02
DOMAIN-SUFFIX,nowe.hk,🇨🇳 Taiwan 02
DOMAIN-SUFFIX,players.brightcove.net,🇨🇳 Taiwan 02
DOMAIN-SUFFIX,s3-ap-southeast-1.amazonaws.com,🇨🇳 Taiwan 02
DOMAIN-SUFFIX,youboranqs01.com,🇨🇳 Taiwan 02
USER-AGENT,HBO%20NOW*,🇨🇳 Taiwan 02
USER-AGENT,HBOMAX*,🇨🇳 Taiwan 02


DOMAIN-KEYWORD,bbc,🇬🇧 UK London 02
DOMAIN,d2z3p34itxwaj7.cloudfront.net,🇬🇧 UK London 02
DOMAIN-KEYWORD,britbox,🇬🇧 UK London 02
DOMAIN-SUFFIX,magni.itv.com,🇬🇧 UK London 02
DOMAIN-KEYWORD,raygun,🇬🇧 UK London 02
DOMAIN-SUFFIX,bb-static.com,🇬🇧 UK London 02
DOMAIN-SUFFIX,appsflyer.com,🇬🇧 UK London 02
DOMAIN-SUFFIX,braze.eu,🇬🇧 UK London 02
DOMAIN-KEYWORD,itv,🇬🇧 UK London 02


DOMAIN-SUFFIX,adrta.com,🇺🇸 USA Seattle 02
DOMAIN-SUFFIX,adsrvr.org,🇺🇸 USA Seattle 02
DOMAIN-SUFFIX,cloudfront.net,🇺🇸 USA Seattle 02
DOMAIN-SUFFIX,crashlytics.com,🇺🇸 USA Seattle 02
DOMAIN-SUFFIX,doubleverify.com,🇺🇸 USA Seattle 02
DOMAIN-SUFFIX,fwmrm.net,🇺🇸 USA Seattle 02
DOMAIN-SUFFIX,innovid.com,🇺🇸 USA Seattle 02
DOMAIN-SUFFIX,movetv.com,🇺🇸 USA Seattle 02
DOMAIN-SUFFIX,omtrdc.net,🇺🇸 USA Seattle 02
DOMAIN-SUFFIX,scorecardresearch.com,🇺🇸 USA Seattle 02
DOMAIN-SUFFIX,serving-sys.com,🇺🇸 USA Seattle 02
DOMAIN-SUFFIX,sling.com,🇺🇸 USA Seattle 02
DOMAIN-SUFFIX,spotxchange.com,🇺🇸 USA Seattle 02
DOMAIN-SUFFIX,tremorhub.com,🇺🇸 USA Seattle 02
DOMAIN-SUFFIX,videoamp.com,🇺🇸 USA Seattle 02

DOMAIN-SUFFIX,cws-hulu.conviva.com,🇺🇸 USA Seattle 02
DOMAIN-SUFFIX,hulu.com,🇺🇸 USA Seattle 02
DOMAIN-SUFFIX,huluad.com,🇺🇸 USA Seattle 02
DOMAIN-SUFFIX,huluim.com,🇺🇸 USA Seattle 02
DOMAIN-SUFFIX,huluqa.com,🇺🇸 USA Seattle 02
DOMAIN-SUFFIX,hulustream.com,🇺🇸 USA Seattle 02
DOMAIN-SUFFIX,footprint.net,🇺🇸 USA Seattle 02
DOMAIN-SUFFIX,tipcdn.com,🇺🇸 USA Seattle 02
DOMAIN-SUFFIX,newrelic.com,🇺🇸 USA Seattle 02
DOMAIN-SUFFIX,imrworldwide.com,🇺🇸 USA Seattle 02
DOMAIN-SUFFIX,moatads.com,🇺🇸 USA Seattle 02
DOMAIN-SUFFIX,fastly.net,🇺🇸 USA Seattle 02
DOMAIN-SUFFIX,omtrdc.net,🇺🇸 USA Seattle 02
DOMAIN-SUFFIX,edgecastcdn.net,🇺🇸 USA Seattle 02
DOMAIN-SUFFIX,hulu.com.akadns.net,🇺🇸 USA Seattle 02
DOMAIN-SUFFIX,cloudfront.net,🇺🇸 USA Seattle 02
DOMAIN-SUFFIX,akamaihd.net,🇺🇸 USA Seattle 02
